# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

#services:
#  - postgresql

#before_install:
#  - psql -c 'CREATE DATABASE rabbit' -U postgres

env:
  global:
    - CODECOV_TOKEN="f3e3945b-c7a2-4b4a-9fbf-0bb70b3db0f4"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - dda.90@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

